github: [dineshmoorthy] # Your GitHub Sponsors username
patreon: # Add your Patreon username if you have one
open_collective: # Add your Open Collective username if you have one
ko_fi: # Add your Ko-fi username if available
tidelift: # Add your Tidelift package if available
community_bridge: # Add your Community Bridge project name
liberapay: # Add your Liberapay username if applicable
issuehunt: # Add your IssueHunt username if you are accepting bounties
lfx_crowdfunding: # Add your LFX Crowdfunding project if applicable
polar: # Add your Polar username if applicable
buy_me_a_coffee: dineshmoorthy # Your Buy Me a Coffee username (if registered)
thanks_dev: # Add your thanks.dev username if applicable
custom: ['https://github.com/sponsors/dineshmoorthy'] # Custom GitHub Sponsors link
